/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KtsContentRouteImport } from './routes/kts-content'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DiscordCommunityRouteImport } from './routes/discord-community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDiscordRouteImport } from './routes/auth.discord'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'

const KtsContentRoute = KtsContentRouteImport.update({
  id: '/kts-content',
  path: '/kts-content',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordCommunityRoute = DiscordCommunityRouteImport.update({
  id: '/discord-community',
  path: '/discord-community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordRoute = AuthDiscordRouteImport.update({
  id: '/auth/discord',
  path: '/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthDiscordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discord-community': typeof DiscordCommunityRoute
  '/join': typeof JoinRoute
  '/kts-content': typeof KtsContentRoute
  '/auth/discord': typeof AuthDiscordRouteWithChildren
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discord-community': typeof DiscordCommunityRoute
  '/join': typeof JoinRoute
  '/kts-content': typeof KtsContentRoute
  '/auth/discord': typeof AuthDiscordRouteWithChildren
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discord-community': typeof DiscordCommunityRoute
  '/join': typeof JoinRoute
  '/kts-content': typeof KtsContentRoute
  '/auth/discord': typeof AuthDiscordRouteWithChildren
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/discord-community'
    | '/join'
    | '/kts-content'
    | '/auth/discord'
    | '/auth/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/discord-community'
    | '/join'
    | '/kts-content'
    | '/auth/discord'
    | '/auth/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/discord-community'
    | '/join'
    | '/kts-content'
    | '/auth/discord'
    | '/auth/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DiscordCommunityRoute: typeof DiscordCommunityRoute
  JoinRoute: typeof JoinRoute
  KtsContentRoute: typeof KtsContentRoute
  AuthDiscordRoute: typeof AuthDiscordRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kts-content': {
      id: '/kts-content'
      path: '/kts-content'
      fullPath: '/kts-content'
      preLoaderRoute: typeof KtsContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord-community': {
      id: '/discord-community'
      path: '/discord-community'
      fullPath: '/discord-community'
      preLoaderRoute: typeof DiscordCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord': {
      id: '/auth/discord'
      path: '/auth/discord'
      fullPath: '/auth/discord'
      preLoaderRoute: typeof AuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof AuthDiscordRoute
    }
  }
}

interface AuthDiscordRouteChildren {
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
}

const AuthDiscordRouteChildren: AuthDiscordRouteChildren = {
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
}

const AuthDiscordRouteWithChildren = AuthDiscordRoute._addFileChildren(
  AuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscordCommunityRoute: DiscordCommunityRoute,
  JoinRoute: JoinRoute,
  KtsContentRoute: KtsContentRoute,
  AuthDiscordRoute: AuthDiscordRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
